name: CD - Blue Green Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: |
          docker build -t strapi-app .
          docker tag strapi-app:latest 775112909184.dkr.ecr.us-east-1.amazonaws.com/strapi-app:latest

      - name: Push Image
        run: |
          docker push 775112909184.dkr.ecr.us-east-1.amazonaws.com/strapi-app:latest

      - name: Deploy via CodeDeploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: taskdef.json
          service: strapi-service
          cluster: strapi-cluster
          codedeploy-application: strapi-codedeploy-app
          codedeploy-deployment-group: strapi-deployment-group